language: python

git:
  depth: 1

branches:
  only:
    - master

matrix:
  include:
    - python: 3.6
# Not supported
#    - python: 3.5
#    - python: 3.4

install:
  - pip install tox-travis coveralls

script:
  - tox -v -c setup.cfg

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then coveralls; fi

notifications:
  email:
    recipients:
      - jcrada@fuzzylite.com
    on_success: always
    on_failure: always
