language: python
python:
  - "3.6"

install:
  - pip install tox-travis

script:
  - tox
  - coverage run --source=fuzzylite setup.py test
  - coverage report -m

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - jcrada@fuzzylite.com
    on_success: always
    on_failure: always
